name: Run Analysis and Send Results

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 6 * * 1-5'  # Run at 6 AM UTC Monday through Friday

jobs:
  analyze-and-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v1
      
      - name: Install dependencies using uv
        run: uv pip install -e .
      
      - name: Run analysis script
        run: uv run src/python/analysis.py
        id: run-analysis
      
      - name: Find output CSV file
        id: find-csv
        run: |
          CSV_FILE=$(find . -name "*.csv" -type f -newermt "$(date -d '1 minute ago' '+%Y-%m-%d %H:%M:%S')" | head -n 1)
          if [ -z "$CSV_FILE" ]; then
            echo "No recent CSV file found"
            exit 1
          fi
          echo "csv_file=$CSV_FILE" >> $GITHUB_OUTPUT
          echo "Found CSV file: $CSV_FILE"
      
      - name: Send email with CSV attachment
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Options Analysis Results - ${{ github.repository }}
          body: |
            Please find attached the latest options analysis results.
            
            This email was automatically generated by GitHub Actions.
          to: ${{ secrets.email1 }},${{ secrets.email2 }}
          from: GitHub Actions
          attachments: ${{ steps.find-csv.outputs.csv_file }}

